#!/usr/bin/perl
#compute how many times each nucleotide occurs in the sequence)
#the DNA sequence
$sequence="CCAATGGATCTTAAGCGCGGCATCGACAAAGCGGTTATCGCAGCTGTTG AAGAGCTGAAGAACCTTTCTGTTCCTTGTTCAGACACTAAAGCTATCGCT CAAGTAGGTACTATCTCTGCGAACTCTGATTCGACAGTAGGTAACATCATT GCTGAAGCGATGGAAAAAGTAGGTCGTGATGGCGTAATCACAGTTGAAG AAGGTCAGGCTCTACAAGACGAGCTAGACGTAGTTGAAGGTATGCAGTT CGACCGCGGTTACCTATCTCCTTACTTCATCAACAATCAAGAAGCCGGTT CTGTTGATCTTGAAAGCCCATTCATTCTTCTAATCGACAAGAAAGTTTCGA ACATCCGTGAACTTCTTCCGACTCTAGAAGCAGTTGCTAAGGCATCTCGT CCACTTCTTATCATCGCTGAAGATGTAGAAGGCGAAGCGCTAGCGACTCT TGTTGTGAACAACATGCGTGG";;
$numOfA=0;
$numOfT=0;
$numOfG=0;
$numOfC=0;

foreach(split //,$sequence) {
if ($_ eq 'A')
{$numOfA++;}
if ($_ eq 'T')
{++$numOfT;}
if($_ eq 'C')
{$numOfC++;}
if($_ eq 'G')
{$numOfG++;}
 }

print "The number Of A is :",$numOfA ,"\n";
print "The number Of T is :",$numOfT,"\n";
print "The number Of C is :",$numOfC,"\n";
print "The number Of G is :",$numOfG,"\n";

exit;
