#!/usr/bin/perl
$sequence="CCAATGGATCTTAAGCGCGGCATCGACAAAGCGGTTATCGCAGCTGTTG AAGAGCTGAAGAACCTTTCTGTTCCTTGTTCAGACACTAAAGCTATCGCT CAAGTAGGTACTATCTCTGCGAACTCTGATTCGACAGTAGGTAACATCATT GCTGAAGCGATGGAAAAAGTAGGTCGTGATGGCGTAATCACAGTTGAAG AAGGTCAGGCTCTACAAGACGAGCTAGACGTAGTTGAAGGTATGCAGTT CGACCGCGGTTACCTATCTCCTTACTTCATCAACAATCAAGAAGCCGGTT CTGTTGATCTTGAAAGCCCATTCATTCTTCTAATCGACAAGAAAGTTTCGA ACATCCGTGAACTTCTTCCGACTCTAGAAGCAGTTGCTAAGGCATCTCGT CCACTTCTTATCATCGCTGAAGATGTAGAAGGCGAAGCGCTAGCGACTCT TGTTGTGAACAACATGCGTGG";;
print  "The DNA is :",$sequence ,"\n" ;
$rna_sequence="";
foreach(split //,$sequence) {
if ($_ eq 'A')
{$rna_sequence.=$_;}
if ($_ eq 'T')
{$rna_sequence.=U;}
if($_ eq 'C')
{$rna_sequence.=$_;}
if($_ eq 'G')
{$rna_sequence.=$_;}
 }
 print "The RNA sequence is :",$rna_sequence ,"\n";

exit;
