#!/usr/bin/perl
#another Solution for extract any subsequence start with “TTCTAT” and position of the first letter in the DNA sequence
$sequence="ACAAAACTCGCCTAAACATGCACTTTGTTTCTAACGTAGACGGCACTCACATCGTTGAGACACTAAAGCCTCTTAACCCAGAAAACACTGTTCCTAGTAGCATCTAAGACATTTACCACTCAAGAAACAATGACGAACGCACACTCTGCGCGTGATTGGTTCTTGGCTGAAGCAGGCGACTCAGCACACGTTGCTGCACTTCGCTGCACTATCAACAAACGCGGCTTCAGTTGCTGAGTTTGGTTTGATACTGACAACATGTTCGAATTCTGGGATTGGGTAGGCGGTCGTTACTCACTATGGTCAGCGATCGGTCTTTCTATCTCACTATCTATCGGCTTCGATAACTTCGCTGAGTTACTCGATGGCGCACACGAGATGGATAACCACTTTGCTTCAACG";
(@sequence1)=split (//,$sequence);
for($d=0;$d<=@sequence1;$d++){
$num=substr($sequence,$d,6);
if ($num eq "TTCTAT"){
print " postion is : $d \n";}
}exit;
