#!/usr/bin/perl
#find the position of every “A” nucleotide in the DNA sequence.
$sequence='TACAAAACTCGCCTAAACATGCACTTTGTTTCTAACGTAGACGGCACTCACATCGTTGAGACACTAAAGCCTCTTAACCCAGAAACAACACTGTTCCTAGTAGCATCTAAGACATTTACCACTCAAGAAACAATGACGAACGCACACTCTGCGCGTGATTGGTTCTTGGCTGAAGCAGGCGACTCAGCACACGTTGCTGCACTTCGCTGCACTATCAACAAACGCGGCTTCAGTTGCTGAGTTTGGTTTGATACTGACAACATGTTCGAATTCTGGGATTGGGTAGGCGGTCGTTACTCACTATGGTCAGCGATCGGTCTTTCTATCTCACTATCTATCGGCTTCGATAACTTCGCTGAGTTACTCGATGGCGCACACGAGATGGATAACCACTTTGCTTCAACG';
$positionOfA="A positions are : ";
$positionOfA=0;

foreach(split //,$sequence){
if($_ eq 'A'){
$positionsOfA.=$positionOfA;
$positionsOfA.=",";}
$positionOfA++;
}
print "the position of every “A” nucleotide in the DNA sequence",$positionsOfA ,"\n\n";
exit;
